"""Infrastructure modules for SPIDER framework."""

from .proxy import ProxyManager, ProxyProvider, ProxyPool, ProxyInfo, ProxyStatus
from .captcha import CAPTCHAManager, CAPTCHAProvider, CAPTCHATask, CAPTCHAType
from .captcha_detection import CAPTCHADetector, CAPTCHAClassifier, CAPTCHAManager as AdvancedCAPTCHAManager, CAPTCHAType as AdvancedCAPTCHAType, CAPTCHADifficulty, CAPTCHADetection, CAPTCHASolution
from .rate_limiter import RateLimiter, AdaptiveRateLimiter, RateLimitConfig, RateLimitStrategy
from .session import SessionManager, CookieManager, Session, Cookie
from .behavior_simulation import BehaviorSimulator, BehaviorManager, BehaviorPattern, MouseMovement, ScrollBehavior, TypingPattern
from .fingerprint_randomization import FingerprintRandomizer, FingerprintManager, BrowserFingerprint, BrowserType, OSFamily
from .human_interactions import HumanInteractionSimulator, InteractionManager, InteractionEvent, InteractionSequence, InteractionType, InteractionContext
from .adaptive_anti_detection import AdaptiveAntiDetectionManager, DetectionAnalyzer, LearningAntiDetection, DetectionEvent, AdaptationAction, DetectionPattern, DetectionType, DetectionSeverity, AdaptationStrategy
from .health_recovery import HealthRecoverySystem, HealthMonitor, RecoveryManager, HealthMetric, FailureEvent, RecoveryPlan, RecoveryResult, HealthStatus, RecoveryAction, FailureType
from .business_metrics import MetricsCollector, BusinessAnalytics, MetricsDashboard, MetricValue, MetricDefinition, MetricDataPoint, MetricAggregation, BusinessKPI, PerformanceBenchmark, MetricType, MetricCategory, MetricGranularity
from .cache import CacheManager, BaseCache, MemoryCache, DiskCache, RedisCache, CacheConfig, CacheStrategy, CacheLevel, CacheStats, CacheEntry, cache_key, cached
from .load_balancer import LoadBalancer, Server, LoadBalancerConfig, LoadBalancingStrategy, HealthStatus, LoadBalancerStats, HealthChecker
from .autoscaler import AutoScaler, ScalingConfig, ScalingStrategy, ScalingPolicy, ScalingAction, ScalingDecision, ScalingEvent, ScalingMetric, MetricsCollector, PredictiveScaler
from .gpu_acceleration import GPUManager, GPUAcceleratedProcessor, GPUDeviceType, GPUInfo, GPUPerformanceMetrics, get_gpu_manager, cleanup_gpu_resources
from .advanced_caching import (
    CacheType, EvictionPolicy, CacheConfig, CacheStats, CacheEntry,
    BaseCacheBackend, RedisCacheBackend, RedisClusterCacheBackend,
    MemcacheBackend, MemoryCacheBackend, HybridCacheBackend,
    AdvancedCacheManager, get_cache_manager, cleanup_cache_resources
)
from .database_optimization import (
    DatabaseType, ConnectionPoolStrategy, QueryOptimizationLevel,
    DatabaseConfig, ConnectionInfo, QueryStats, DatabaseMetrics,
    ConnectionPool, DatabaseOptimizer, get_database_manager, cleanup_database_resources
)

__all__ = [
    "ProxyManager",
    "ProxyProvider",
    "ProxyPool",
    "ProxyInfo",
    "ProxyStatus",
    "CAPTCHAManager",
    "CAPTCHAProvider",
    "CAPTCHATask",
    "CAPTCHAType",
    "CAPTCHADetector",
    "CAPTCHAClassifier",
    "AdvancedCAPTCHAManager",
    "AdvancedCAPTCHAType",
    "CAPTCHADifficulty",
    "CAPTCHADetection",
    "CAPTCHASolution",
    "RateLimiter",
    "AdaptiveRateLimiter",
    "RateLimitConfig",
    "RateLimitStrategy",
    "SessionManager",
    "CookieManager",
    "Session",
    "Cookie",
    "BehaviorSimulator",
    "BehaviorManager",
    "BehaviorPattern",
    "MouseMovement",
    "ScrollBehavior",
    "TypingPattern",
    "FingerprintRandomizer",
    "FingerprintManager",
    "BrowserFingerprint",
    "BrowserType",
    "OSFamily",
    "HumanInteractionSimulator",
    "InteractionManager",
    "InteractionEvent",
    "InteractionSequence",
    "InteractionType",
    "InteractionContext",
    "AdaptiveAntiDetectionManager",
    "DetectionAnalyzer",
    "LearningAntiDetection",
    "DetectionEvent",
    "AdaptationAction",
    "DetectionPattern",
    "DetectionType",
    "DetectionSeverity",
    "AdaptationStrategy",
    "HealthRecoverySystem",
    "HealthMonitor",
    "RecoveryManager",
    "HealthMetric",
    "FailureEvent",
    "RecoveryPlan",
    "RecoveryResult",
    "HealthStatus",
    "RecoveryAction",
    "FailureType",
    "MetricsCollector",
    "BusinessAnalytics",
    "MetricsDashboard",
    "MetricValue",
    "MetricDefinition",
    "MetricDataPoint",
    "MetricAggregation",
    "BusinessKPI",
    "PerformanceBenchmark",
    "MetricType",
    "MetricCategory",
    "MetricGranularity",
    "CacheManager",
    "BaseCache",
    "MemoryCache",
    "DiskCache",
    "RedisCache",
    "CacheConfig",
    "CacheStrategy",
    "CacheLevel",
    "CacheStats",
    "CacheEntry",
    "cache_key",
    "cached",
    "LoadBalancer",
    "Server",
    "LoadBalancerConfig",
    "LoadBalancingStrategy",
    "HealthStatus",
    "LoadBalancerStats",
    "HealthChecker",
    "AutoScaler",
    "ScalingConfig",
    "ScalingStrategy",
    "ScalingPolicy",
    "ScalingAction",
    "ScalingDecision",
    "ScalingEvent",
    "ScalingMetric",
    "MetricsCollector",
    "PredictiveScaler",
    "GPUManager",
    "GPUAcceleratedProcessor",
    "GPUDeviceType",
    "GPUInfo",
    "GPUPerformanceMetrics",
    "get_gpu_manager",
    "cleanup_gpu_resources",
    "CacheType",
    "EvictionPolicy",
    "CacheConfig",
    "CacheStats",
    "CacheEntry",
    "BaseCacheBackend",
    "RedisCacheBackend",
    "RedisClusterCacheBackend",
    "MemcacheBackend",
    "MemoryCacheBackend",
    "HybridCacheBackend",
    "AdvancedCacheManager",
    "get_cache_manager",
    "cleanup_cache_resources",
    "DatabaseType",
    "ConnectionPoolStrategy",
    "QueryOptimizationLevel",
    "DatabaseConfig",
    "ConnectionInfo",
    "QueryStats",
    "DatabaseMetrics",
    "ConnectionPool",
    "DatabaseOptimizer",
    "get_database_manager",
    "cleanup_database_resources",
]
